version: '3'

services:

  php:
    build: ./docker/php
    depends_on:
      - db
    volumes:
      - ./:/app:cached
      - /home/zori/.composer/cache:/root/.composer/cache

  db:
    image: mariadb
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel-blog
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  nginx:
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/app:cached
    depends_on:
      - php